### ISSUE TITLE
Any options for self-hosting the server?

### ISSUE THREAD

**Issue by filipesmedeiros** [MyScript/iinkTS#8]
Hello!

I was wondering if there are any options for self-hosting the web server. Is it open source (or at least on request) somehow?

Mind you that I would be open to paying for it, of course.

Congrats on the great tool, it works really nicely!

Best, Filipe.

**Comment by edgard-myscript** [comment]
Hello Filipe,

Yes, MyScript is offering such solution, called MyScript Server. You can have a look on its description in the DevPortal Documentation [here](https://developer.myscript.com/docs/interactive-ink/3.2/web/overview/introduction/#myscript-cloud-and-myscript-server)

Feel free to [contact us](https://developer.myscript.com/contact/quote-cloud-hwr) and share more details on how we can help you.

Regards, Edgard

**Comment by filipesmedeiros** [comment]
Thank you! I missed that
